extends: ["spectral:oas"]

rules:
  
  acme-path-pattern-with-hyphens:
    description: Ensures URI paths are in kebab case
    message: "Path {{property}} should be in kebab case"
    severity: error
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^[a-z][a-z0-9\\-]*$"

