openapi: 3.1.0
info:
  title: Product Catalog API
  version: '1.0'
  description: 'The Product Catalog API enables customers browse Acme Pet Supplies great range of pet products and their product reviews. '
  summary: Browse Acme Pet Supplies catalog
  contact:
    name: John Smit
    email: john.smith@acme-pet-supplies.co.uk
    url: acme-pet-supplies.co.uk/docs
  termsOfService: 'http://acme-pet-supplies.co.uk/terms'
servers:
  - url: 'http://api.acme-pet-supplies.com/v1/catalog'
    description: Production
  - url: 'http://dev.acme-pet-supplies.com/v1/catalog'
    description: Development
  - url: 'http://staging.acme-pet-supplies.com/v1/catalog'
    description: Staging
paths:
  /product-categories:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  productCategories:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductCategory'
                required:
                  - productCategories
              examples:
                example-1:
                  value:
                    productCategories:
                      - productCategoryId: 1e32231d-b8a1-4145-b539-820301c2af64
                        name: Dogs
                        numberOfProducts: '10'
                        productLinks: string
      operationId: listProductCategories
      description: 'List all product categories, providing the number of products in a category.'
  '/product-categories/{productCategory}/products':
    parameters:
      - schema:
          type: string
        name: productCategory
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: listProductsInCategory
      description: 'List all products in a category, providing ordering and pagination parameters'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/ProductLinks'
                meta:
                  type: string
            examples:
              example-1:
                value:
                  productSumary: string
                  pa: string
  '/products/{productId}':
    parameters:
      - schema:
          type: string
        name: productId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: viewProduct
      description: View a product's details.
  '/product-reviews/{productReviewId}':
    parameters:
      - schema:
          type: string
        name: productReviewId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: listProductReviews
      description: Get all reviews for a product.
components:
  schemas:
    Product:
      title: Product
      x-stoplight:
        id: rqw04761l3s4d
      type: object
      description: 'An item in Acme''s pet supplies catalog. '
      properties:
        productId:
          type: string
          format: uuid
          example: dcd53ddb-8104-4e48-8cc0-5df1088c6113
        name:
          type: string
          minLength: 1
          maxLength: 50
          example: Acme Uber Dog Rope Toy
        description:
          type: string
          maxLength: 300
          minLength: 0
          example: 'Acme Uber Dog Rope Toy provides hours of fun for your dog. Great for bouncing, throwing and catching. '
        price:
          type: number
          minimum: 0
          maximum: 1000000
          example: 100
        keywords:
          type: array
          maxItems: 20
          minItems: 0
          uniqueItems: true
          items:
            type: string
            example: dog toy
        productCategories:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/ProductCategoryLinks'
        reviewRating:
          type: integer
          minimum: 1
          maximum: 5
          format: int32
          example: 5
        numberOfReviews:
          type: integer
          example: 10
          format: int32
      required:
        - productId
        - name
        - price
      examples:
        - productId: dcd53ddb-8104-4e48-8cc0-5df1088c6113
          name: Acme Uber Dog Rope Toy
          description: 'Acme Uber Dog Rope Toy provides hours of fun for your dog. Great for bouncing, throwing and catching. '
          price: 100
          keywords:
            - dog toy
          productCategories:
            - name: Dogs
              uri: /dogs
          reviewRating: 5
          numberOfReviews: 10
    ProductCategoryLinks:
      title: ProductCategoryLinks
      x-stoplight:
        id: w8av1b76lnbc3
      type: object
      properties:
        name:
          type: string
          minLength: 0
          maxLength: 20
          example: Dogs
        uri:
          type: string
          example: /dogs
          format: uri-reference
      required:
        - name
        - uri
      examples:
        - name: Dogs
          uri: /dogs
    ProductCategory:
      title: ProductCategory
      x-stoplight:
        id: elt8m3eura182
      type: object
      examples:
        - productCategoryId: 1e32231d-b8a1-4145-b539-820301c2af64
          name: Dogs
          numberOfProducts: '10'
          productLinks:
            - name: Acme Dog Rope Toy
              uri: /products/b3daf590-bb20-473d-92a0-b4f8c4f5f9d8
      properties:
        productCategoryId:
          type: string
          format: uuid
          example: 1e32231d-b8a1-4145-b539-820301c2af64
        name:
          type: string
          example: Dogs
          maxLength: 20
          minLength: 0
        numberOfProducts:
          type: integer
          example: '10'
          minimum: 0
          maximum: 10000000
        productLinks:
          format: uri-reference
          type: array
          items:
            $ref: '#/components/schemas/ProductLinks'
      required:
        - productCategoryId
        - name
        - numberOfProducts
        - productLinks
    ProductLinks:
      title: ProductLinks
      x-stoplight:
        id: yj6ij912uwywo
      type: object
      examples:
        - name: Acme Dog Rope Toy
          uri: /products/b3daf590-bb20-473d-92a0-b4f8c4f5f9d8
      properties:
        name:
          type: string
          example: Acme Dog Rope Toy
        uri:
          type: string
          format: uri-reference
          example: /products/b3daf590-bb20-473d-92a0-b4f8c4f5f9d8
          maxLength: 200
          minLength: 0
    ProductReview:
      title: ProductReview
      x-stoplight:
        id: ql1ifoos1mvp2
      type: object
      properties:
        productReviewId:
          type: string
          format: uuid
          example: a264188f-b5ba-4c5c-8f9c-d0e9348b14dc
        content:
          type: string
          example: This dog toy is great! My dog loved to play with it. I thoroughly recommend.
          maxLength: 500
          minLength: 0
        rating:
          type: integer
          minimum: 1
          maximum: 5
          example: 5
        authorName:
          type: string
          example: Jill Baker
        submittedDate:
          type: string
          format: date-time
          example: '2022-04-12T23:20:50.52Z'
      required:
        - productReviewId
        - content
        - rating
        - authorName
        - submittedDate
  securitySchemes:
    apiKey:
      name: 142a3e7e-6075-40e8-9bad-136a136f335d
      type: apiKey
      in: header
      description: ''
