extends: ["spectral:oas"]

rules:
  
  acme-ensure-paths-kebab-case:
    description: Ensures URI paths are in kebab case
    message: "Path {{property}} should be in kebab case"
    severity: error
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^(\/|[a-z0-9-.]+|{[a-zA-Z0-9]+})+$"

