name: Commit Stage Merge Action

on: 
  push: 
    branches:
      - main

env:
  run_number: ${GITHUB_RUN_NUMBER}

permissions:
  checks: write

jobs:
  commit-stage-merge:
    name: Commit Stage Merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out pr branch
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Portman 
        run: |
          npm install -g @apideck/portman
      - name: Generate Postman collections for external consumers
        run: |
          portman --cliOptionsFile test-config/ci-portman-cli-options.json
      - name: "Zip API definition, Postman collection"
        run: |
            zip artifacts.zip reference/product-catalog-api.oas.yaml output/postman.collection.json
      - name: "Setup artifact repository CLI (Jfrog CLI)" 
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ENV_1: ${{ secrets.JF_SECRET }}
      - name: "Upload to artifact repository (Jfrog Artifactory)"
        run: |
            jf rt ping
            # jf rt u artifacts.zip default-api-generic-local/com.acmeps/product-catalog-api/artifacts.${{ env.run_number }}.zip 
            # jf rt bp


            eyJ2ZXJzaW9uIjoyLCJ1cmwiOiJodHRwczovL2FjbWVwZXRzdXBwbGllcy5qZnJvZy5pby8iLCJhcnRpZmFjdG9yeVVybCI6Imh0dHBzOi8vYWNtZXBldHN1cHBsaWVzLmpmcm9nLmlvL2FydGlmYWN0b3J5LyIsImRpc3RyaWJ1dGlvblVybCI6Imh0dHBzOi8vYWNtZXBldHN1cHBsaWVzLmpmcm9nLmlvL2Rpc3RyaWJ1dGlvbi8iLCJ4cmF5VXJsIjoiaHR0cHM6Ly9hY21lcGV0c3VwcGxpZXMuamZyb2cuaW8veHJheS8iLCJtaXNzaW9uQ29udHJvbFVybCI6Imh0dHBzOi8vYWNtZXBldHN1cHBsaWVzLmpmcm9nLmlvL21jLyIsInBpcGVsaW5lc1VybCI6Imh0dHBzOi8vYWNtZXBldHN1cHBsaWVzLmpmcm9nLmlvL3BpcGVsaW5lcy8iLCJhY2Nlc3NUb2tlbiI6ImV5SjJaWElpT2lJeUlpd2lkSGx3SWpvaVNsZFVJaXdpWVd4bklqb2lVbE15TlRZaUxDSnJhV1FpT2lKRFpTMW1hMjlyUW01b1VYTnRTREpqWmxsRVpqVkZPVXBaVFVaQ05rWXhOSGxDYUVzNVNYSjJhWEE0SW4wLmV5SmxlSFFpT2lKN1hDSnlaWFp2WTJGaWJHVmNJanBjSW5SeWRXVmNJbjBpTENKemRXSWlPaUpxWm1GalFEQXhaelo2WkhvME1IUTVkR2hpTUdabmJXdGplVEl3TkhsNVhDOTFjMlZ5YzF3dmFXdGxibTVoUUdsclpXNXVZUzV1WlhRaUxDSnpZM0FpT2lKaGNIQnNhV1ZrTFhCbGNtMXBjM05wYjI1elhDOTFjMlZ5SWl3aVlYVmtJanBiSW1wbWNuUkFNREZuTm5wa2VuQTJOemhxT0hveGJqZG5kSGszWkRGbFpEY2lMQ0pxWm5oeVFEQXhaelo2Wkhvd2NERjJNRFIwZVRVM1pHSTBjMnA2TVhrNElsMHNJbWx6Y3lJNkltcG1ZV05BTURGbk5ucGtlalF3ZERsMGFHSXdabWR0YTJONU1qQTBlWGtpTENKbGVIQWlPalE0TVRBMU1UYzBPVFVzSW1saGRDSTZNVFkxTmpreE56UTVOU3dpYW5ScElqb2lOelZsWXpka1lXVXRZalkyTlMwME1URm1MVGxoTVdVdE9HWmlaRFZqWVRsaE9USTJJbjAuazF2WEpFMlBjQmpsbWVWZGxuUlRvSjk0MWNkM1NMdzBPQzVEMUNWcFlhZ3l3VDN6UUFTYWk3dmNmWmlFanZFNVQzQ3d1c0VkRmRqQl9TVDRxUldEeVhwWVA4ZUhOWmRZbDh6SmsyY19QX181aTZ3cld6S3IwWVlmM09LMWZ4WmVyV3NWQXVxZ2R0VV9vOEgybEdnVFpIa2pmN2liNi1KUi1UZ09iT25URFdqS0JMWk5xT2JrUTNiX1FxeFNSSTA0bkxCUFVWYm5uV0xiM2t0aUZFSzdvcDVDc3lCamM4Sml5NmplbS0wR0VrQzZxTjY0eDNHbmlfTDJvVnFqS01WSUJSc245d1ByTmtHNzM4aDItQnBnSHJ2RnBZeVF2cC1haDBqVWhYQXNQb2xuQ0VtV3ZsdzZERUpUTjlKOTVsODMtZVJNSFE1TEIxT2lLNXhoQTl3bHJnIiwic2VydmVySWQiOiJhY21lcGV0c3VwcGxpZXMifQ==
